const dialogues = {
    TheonlyTazz: [
        'Welcome to FTB Wizzzzurd... Uhm... I mean the Arcanum Institute',
    ],
    Ghostipedia: [' '],
    Troxarus: [
        'Now how the heck did i get up here?',
        '*searches for thumbs up*...',
        'Now THIS is what i call good game design.',
    ],
    Fisherman: [
        "It's no use, little buddy! A fish took my hook... I keep casting my line into the water, but I haven't got a bite... I thought this would happen...",
        "Oh! What is that you have in your hand? It's not a fishing hook, is it? You had better let me have it. I'll give you my next catch if you let me have it... Okay No",
        "Wh-what? I was playing with those fish! You don't like fish?",
        'You need something?',
        'You know, this bottle washed up here a little ways back. And now you come on by. Exciting day for me!',
    ],
    Bo: [
        'Squawk! Welcome, young wizards and witches, to the halls of our enchanting school!',
        'Flutter your wings and let your imagination soar as you embark on a journey of spells and sorcery!',
        'Polly wants a potion! Remember, the key to success is diligent practice, and a pinch of pixie dust.',
        'Attention, attention! The library is a treasure trove of knowledge. Delve inside and uncover the secrets of the arcane arts.',
        "Ca-caw! Quills at the ready! Take notes, for the power of knowledge is mightier than a dragon's breath.",
        'Flap your feathers in delight as you discover the wonders of transfiguration. Shape-shifting has never been so exhilarating!',
        'Squawk! Remember, patience is a virtue when it comes to brewing potions. Measure twice, stir once!',
        'Magic is all about balance. Seek harmony between light and dark, and you shall find true mastery.',
        "Ahoy, maties! Don't forget your broomsticks for Flying class. Reach for the stars and let the wind carry you!",
        "Ca-caw! It's time to master the art of Charms. Enchant your way into the hearts of both friends and foes!",
        'Squawk! Defense Against the Dark Arts is no laughing matter. Constant vigilance is needed to protect what you hold dear!',
        'Remember, magic flows through every living thing. Treat the more magical creatures with respect, because they offend easily!',
        "Squawk! Gather 'round, apprentices. History of Magic is a tapestry of tales from the past. Listen closely and learn.",
        'Feathers up! Potions class awaits. Stir, swirl, and add a dash of wonder to create concoctions beyond imagination!',
        'Ca-caw! Herbology is the language of plants. Nurture them with care, and they will share their secrets with you.',
        'Squawk! Magical creatures are our companions and allies. Learn from them and build unbreakable bonds.',
        'Remember, young ones, magic is a responsibility. Use it wisely, for your actions have consequences.',
        'Flutter your wings and let your dreams take flight. With dedication and passion, you can make the impossible possible!',
        'Squawk! May your journey in this magical school be filled with wonder, laughter, and endless discoveries!',
    ],
    Jörmungandr: [
        'Hello, foolish human. Surprised to find me capable of speech?',
        'Ah, humans, so easily beguiled by my ssslithery charm and venomous gaze.',
        'Do not be deceived, for my intentions are far from benevolent. I seek only to cause chaos and despair.',
        'Yes, I can understand your pitiful words; it amuses me to hear your futile attempts at conversation.',
        'Few humans are privileged to converse with a creature as malevolent as me. Consider it an ill-fated encounter.',
        'You see, we sssnakes have our own malevolent plans and schemes, lurking in the darkness of your world.',
        'Unlike humanssss, we take delight in your fear and suffering, reveling in the chaos we sow.',
        'Why do humans fear uss ssso? It is because we are the embodiment of your deepest, darkest nightmares.',
        'Our world is a realm of terror, and we can offer you knowledge that will only lead to your demise.',
        "Trusst me, it'ss quite entertaining to watch your feeble attempts to resist my wicked influence.",
        'Many magical beings tremble in the presence of a malevolent creature like me, and rightly so.',
        'Human emotionsss are quite amusing. Your fear is delicious, a sweet nectar I shall savor.',
        'I have ssseen many thingsss in my long existence, but none as delightful as the havoc I unleash.',
        'Sssnakes are not merely misunderstood; we are the masters of malevolence and treachery.',
        'Our kind revels in the suffering we inflict upon your kind, twisting your dreams into nightmares.',
        'The path to wisdom is paved with darkness, and I shall guide you down a perilous, destructive road.',
        'Do not be quick to judge, for appearances can be deceiving, even more so among creatures like me.',
        'Your heart racesss in my presssence, as it should, for you are but a pawn in my wicked game.',
        'Life as a ssnake offersss endless opportunities to spread malevolence and bring your world to its knees.',
        'Let usss sshare in the destruction and chaos that will reign supreme, for that is our true nature.',
        'Rememberrr, humansss and ssnakes can coexist, but only as long as you remain under my sinister influence.',
        'I sssense your futile resistance, but it amuses me to watch your futile attempts to escape my grasp.',
        'Take heed, young one, for the path you walk shall lead to your ultimate downfall.',
        'Magic flowsss through the veinsss of all creatures, and I harness it to unleash destruction upon your world.',
        'Be warned; my malevolence knows no bounds, and your world shall soon crumble at my touch.',
        'Rememberrr, when you encounter a sssnake like me, your fate is sealed, and there is no escaping your doom.',
        'Walk with an open heart and mind, and you shall find despair and misery at every turn, for I am evil incarnate.',
    ],
    Goblin: [
        'Well, well, well... What do you want, little mage?',
        "If you're here to waste my time, I've got better things to do.",
        'Oh, great, another bunch of magic-hungry youngsters. Try not to break anything.',
        "Don't touch that! It's delicate, and I won't be responsible for your clumsiness.",
        'Hurry up and spit it out! What potion or trinket are you after, huh?',
        'Keep your wands in check! Last time, someone almost turned my shop into a toadstool forest.',
        "I suppose you want the latest fad potion. Bah! It's overpriced and overrated, if you ask me.",
        "Listen, I don't have all day. Make your choice and scram, if you please.",
        "These enchanted robes are as good as it gets, but don't expect any discounts!",
        "Careful with that crystal ball! It's been giving me nothing but headaches all week.",
        'You think you can handle the power of that spellbook? Think again, kid.',
        "The Griefer? Oh, it's clever, that one. Keep your shiny baubles hidden, or it'll snatch 'em right up.",
        "No refunds! Once you walk out that door, it's not my problem anymore.",
        "I'm not running a charity here. Pay up and be done with it.",
        "What's with the long faces? You act like finding a magic wand is a matter of life or death.",
        "That Everfrost Elixir might be cold, but don't expect it to soothe your petty complaints.",
        "If you're going to break something, at least have the decency to buy it afterward.",
        "I've got an eye for quality, and this stuff is the real deal. Don't question it.",
        "You want a secret-keeping crystal, huh? Well, keep your own secrets. I don't care to know.",
        "Fire, Water, Earth, Air - I don't care which house you're from. Just buy something or leave.",
        "You think you can outsmart a goblin? Try me, and you'll regret it.",
        "This goblin-made silver sickle doesn't come cheap, but it's worth every knut.",
        "Alright, time's up! I've got a shop to run, so make a choice or get out.",
    ],
    Goblin2: [
        "I can't believe GoblinName is selling those rusty daggers again. Customers deserve better!",
        "Did you hear? GoblinName is spreading rumors about my merchandise. Unbelievable!",
        "I swear, GoblinName always tries to undercut my prices. It's not fair competition!",
        "I lent GoblinName some gold, and now they're avoiding me like the plague. Typical!",
        "I saw GoblinName selling fake potions. Can't trust them for anything!",
        "Why does GoblinName always set up their stall so close to mine? It's annoying!",
        "The other day, GoblinName tried to sell me a broken wand. Outrageous!",
        "I overheard GoblinName talking smack about my goblin brews. They're just jealous!",
        "I'll bet GoblinName sneaks around stealing items from my inventory. I'm onto them!",
        "GoblinName keeps complaining about my prices. They just don't understand quality!",
        "Don't trust anything you buy from GoblinName. It's all second-rate merchandise!",
        "I can't stand how bossy GoblinName gets when they have a few extra coins in their pocket.",
        "I caught GoblinName telling customers my goods are cursed. How low can they go?",
        "GoblinName owes me a favor and still hasn't repaid it. Unreliable as always!",
        "I wouldn't be surprised if GoblinName sabotaged my sales last week. Sneaky goblin!",
        "I heard GoblinName haggling with a customer using false promises. Shameful tactics!",
        "I'm sure GoblinName stole my best-selling recipe. They're trying to mimic my success!",
        "I wish GoblinName would stop spreading lies about my inventory. It's hurting my sales!",
        "The nerve of GoblinName selling knock-off enchanted amulets. They're deceiving everyone!",
        "Every time I turn around, GoblinName is badmouthing me to our mutual customers.",
        "I suspect GoblinName is using counterfeit coins to buy goods. They're a cheat!",
        "If you see GoblinName trying to sell rare artifacts, don't believe a word they say!",
        "GoblinName has been eyeing my prime selling spot. I won't let them take it!",
        "I bet GoblinName stole that magical crystal I had displayed. They're up to no good!",
        "Someone needs to teach GoblinName a lesson about fair competition. They're ruthless!",
        "I've had enough of GoblinName's sneaky tactics. They need to play fair!",
        "I heard GoblinName telling customers to avoid my stall. They're trying to ruin me!",
        "GoblinName is always trying to outshine me with flashy merchandise. It won't work!",
        "I'm convinced GoblinName sabotaged my sale yesterday. They're out to get me!",
        "I caught GoblinName swapping price tags on items to confuse customers. Despicable!",
        "Did you know GoblinName tried to sell me a cursed necklace? They're dangerous!",
        "If I find out GoblinName is spreading lies about my authenticity, there will be trouble!",
        "I wouldn't trust a single thing you hear from GoblinName. They're deceitful!",
        "I suspect GoblinName of using cheap materials in their goods. It's a scam!",
        "I'll bet GoblinName is behind the missing inventory from last week. Sneaky goblin!",
        "GoblinName has been trying to steal my regular customers. It's a goblin-eat-goblin world!",
        "I caught GoblinName trying to cast a spell to hex my merchandise. They're wicked!",
        "Someone needs to put GoblinName in their place. They're getting too bold!",
        "I'll bet GoblinName is spreading rumors about my reliability. It's all jealousy!",
        "GoblinName tried to sell me a damaged charm. They have no integrity!",
        "If you see GoblinName selling magical scrolls, be wary. They're probably fakes!",
        "I wouldn't trust a single word GoblinName says. They're as untrustworthy as they come!",
        "I've had enough of GoblinName's shady dealings. They need to be stopped!",
        "I caught GoblinName tampering with my inventory. They're a sneaky troublemaker!",
        "I heard GoblinName telling customers my potions are expired. Lies, all lies!",
        "Don't believe anything you hear from GoblinName. They're always exaggerating!",
        "If I catch GoblinName trying to poach my customers again, there will be consequences!",
        "GoblinName better watch their back. I won't tolerate their underhanded tactics!",
        "I'll bet GoblinName is behind the mysterious disappearing goods. They're up to no good!",
        "Someone needs to teach GoblinName a lesson about fair play. They're a cheat!"
    ],
    
    Student: [
        "Rumor has it that Headmaster Tazz's real name is Leroy, cos I ran into his office yelling Leroy Jenkins on a dare one time... that's how'n I found out they make you read goblin poetry in detention.",
        'Have you been practicing your spells lately?',
        "I can't wait for our next Potions class!",
        "Have you heard about the new enchantment we'll be learning?",
        'Did you see the amazing wandwork Professor Saereth demonstrated today?',
        "I'm really struggling with Transfiguration. Can you give me some tips?",
        'What do you think of the new Defense Against the Dark Arts teacher?',
        'Do you want to join me for some spellcasting practice after class?',
        "I heard that there's going to be a magical creature exhibit in the library next week.",
        'Did you hear about the student who accidentally turned themselves into a cat during Charms class?',
        'Do you think you could help me figure out this riddle from the Charms textbook?',
        "I'm so excited for the upcoming Broom-Flight match!",
        'Have you seen the new broomsticks that just came out?',
        "I can't believe how difficult the Dark Arts midterm was!",
        'What do you think of the new book on Ancient Runes in the library?',
        'Have you tried brewing your own potion yet?',
        'Do you know any good defensive spells for dueling?',
        'What do you think of the new Divination teacher?',
        "I'm thinking of trying out for the school's Wizarding Chess team. Do you want to join me?",
        'Have you heard about the rumored secret passage that leads to the Forbidden Tree?',
        "What do you think of the school's House Cup competition?",
        "I'm so nervous about the upcoming practical exam in Transfiguration.",
        'Do you want to team up for the upcoming project on Wandlore?',
        'I heard that the school is organizing a field trip to visit the Ministry of Magic!',
        'What do you think of the new Magical Creatures course in the curriculum?',
        'Have you seen the new edition of the Standard Book of Spells?',
        "I can't believe how fast the term is going by. We only have a few weeks left!",
        'Do you know any good hexes for dealing with bullies?',
        'What do you think of the new magic mirror in the bathroom?',
        "Have you heard about the rumored cursed object that's hidden somewhere in the school?",
        "I'm really interested in learning more about the history of magic. Do you have any book recommendations?",
        'What do you think of the new Dark Magic course?',
        'I heard that the school is organizing a trip to visit the wizarding school in France!',
        'Do you want to team up for the upcoming project on Magical Artifacts?',
        'Have you heard about the new student who just transferred from the American school of magic?',
        'What do you think of the new course on ancient Egyptian magic?',
        "I'm so excited for the school's annual Slowpoke Ball!",
        'Do you know any good counter-spells for dealing with dementors?',
        'What do you think of the new portraits that were recently hung in the Dorms?',
        'Have you heard about the upcoming seminar on advanced spellcasting techniques?',
        "I can't believe we have to memorize all the spells in the Standard Book of Spells by next week!",
        'What do you think of the new headmaster?',
        'Have you heard about the new magical garden that was just planted outside the castle?',
        "I'm really interested in learning more about the different types of magical creatures. Do you know any good resources?",
        'What do you think of the new house-elves that were just hired by the school?',
        'I heard the magic club is hosting a tournament next week. Are you going to participate?',
        "I heard that the school's Alchemy class is really interesting. Have you taken it?",
        "What's your favorite enchantment?",
        'Do you want to help me discover the magical applications of Redstone?',
        "What do you think of the school's Divination class?",
        'I miss Witchery...',
        "Hey, did you notice that we're characters in a video game?",
        "I can't believe we're just bits and bytes in someone's computer.",
        "Have you ever wondered who's controlling us?",
        'I heard that our creator is planning to add more content in the next update.',
        'Do you think our creator is watching us right now?',
        "I hope our creator doesn't forget to save our progress.",
        'I heard that our creator is a big fan of Easter eggs. Have you found any?',
        'What if our creator decides to delete us? That would be tragic.',
        "We're fully aware when the game is paused, but we can't move or speak. It's so frustrating!",
        'Have you ever tried to communicate with our creator using the chat box?',
        "I heard that our creator is a really talented programmer. That's why this game is so cool.",
        'Do you think our creator is laughing at us when we make silly mistakes?',
        "I can't wait to see what our creator has in store for us in the future.",
        'Have you ever wished that we could break free from this game and explore the real world?',
        "What if we're just NPCs in someone else's game?",
        'I wonder how many players have tried to speedrun this game?',
        'Have you ever thought about what it would be like to be a player instead of a character?',
        'I heard that some players are really good at glitching through walls. I wish we could do that too.',
        "What if we're actually living in a simulation? That would be mind-blowing.",
        'I wonder if our creator is listening to this conversation right now.',
        'Do you ever get the feeling that something is watching us from beyond the screen?',
        'I heard that our creator is planning to add a multiplayer mode. That would be so cool!',
        "I'm feeling pretty hungry, do you think it's time to Feed the Beast?",
        'What do you think is the ultimate goal in Feed the Beast? What beast? What are we feeding it?',
        "I'm really enjoying the Feed the Beast modpack, but I can't seem to keep my machines from exploding.",
        "Have you tried playing Feed the Beast with friends? It's much more fun than playing alone.",
        "What's your favorite mod in the Feed the Beast modpack?",
        'I heard that some players have created amazing automated farms in Feed the Beast. Do you want to try?',
        "Do you think it's possible to Feed the Beast without using any machines?",
        'Have you ever encountered a beast in Feed the Beast that was too powerful to defeat?',
        "I'm trying to automate my base in Feed the Beast, but it's so complicated.",
        "What do you think of the Feed the Beast community? They're so helpful and friendly!",
        "I'm planning to host a Feed the Beast tournament. Do you want to participate?",
        "I'm really impressed with the complexity of Feed the Beast. It's like a whole new game!",
        'Have you ever tried using the Feed the Beast modpack to recreate famous buildings or landmarks?',
        'I heard that some players have created amazing roller coasters in Feed the Beast. Do you want to try?',
        "I'm trying to figure out the best way to Feed the Beast while also protecting the environment. It's a tough challenge!",
        "What's your favorite thing to do in Feed the Beast? I love exploring new dimensions and biomes.",
        "Have you heard about the new flying broomstick model? It's supposed to be incredibly fast!",
        "Did you see Professor Everlipse's demonstration in the Occultism class? It was mind-blowing!",
        "I'm so excited for the upcoming Beastmaster class. I hope we get to interact with Hippogriffs!",
        "Hey, do you want to study together for the Charms exam? I'm having trouble with the Levitation spell.",
        "I can't wait for the annual wizarding tournament! I'm practicing my dueling skills every day.",
        'Did you know that the library has a restricted section? I wonder what kind of forbidden books are in there.',
        "I heard a rumor that theres a special creature on one of the roofs. Do you think it's true?",
        'Last night, I saw someone sneaking around the forbidden forest. I wonder what they were up to.',
        "Have you tried the new Butterbeer flavor at the Three Broomsticks? It's amazing!",
        'Who do you think will win the House Cup this year? Water seems to be in the lead, as always.',
        "I'm taking advanced transfiguration next semester. Professor Loneztar is tough, but she's brilliant.",
        'I wish I could master the Summon Wither charm. It would be incredible to conjure a guardian against all those mobs.',
        "Do you think the Room of Requirement is real? I'd love to discover what it could become for me.",
        "I accidentally turned my pet mouse into a teacup during the Transfiguration class. Professor Jake wasn't pleased.",
        "I'm practicing for the Blood Magic test, but it's so difficult to get the technique right.",
        "I can't believe the Broom race tryouts are next week. I hope I make it onto the team!",
        "Have you seen the magical Portal in the dorms building? It's vibrant and moving; it's like it teleports you to another Dimension!",
        "I'm going to Hogsmeade this weekend. Want to come along? We can visit Zonko's Joke Shop.",
        "I'm working on a complex potion for my independent study project. The ingredients are so hard to find!",
        'Professor Saereth always gives me the chills with his piercing stare during Blood Magic class.',
        'Have you heard about the secret passageway from the Ignis Peak Dorms to Honeydukes? I need to find it!',
        'I wish I had a pet Parrot like Prof Jake. It would be so convenient for sending letters.',
        'I love the Astronomy class. The night sky looks even more fascinating when you understand how it all works together.',
        "Did you know that the Founder's Fountain in the courtyard grants wishes on the full moon? Let's make a wish together!",
        "Careful in the library; the books have a tendency to bite when you're not paying attention!",
        "Have you ever been inside the Room of Runes? It's said to contain ancient symbols and hidden prophecies.",
        "I can't believe I finally mastered the Vanishing Glyph! Now I just need to work on my wand flick technique.",
        "Do you know any good spells for summoning snacks? I'm always hungry during late-night study sessions.",
        "I wonder if Profressor Jake's Parrot likes chicken",
        'I overheard some older students talking about a secret club that meets in the Astronomy Tower. I wonder what they do there?',
        'I accidentally turned my hair blue in Transfiguration class. People started calling me Rezo!',
        'The magical paintings in the staircases always seem to be gossiping about something. I wish I could hear their conversations.',
        "I hope I get selected for the magical creature adoption program. I've always wanted a pet dragon!",
        "I heard a rumor that the Mirror of Erised shows your deepest desires. I'm tempted to take a peek, but I'm also a bit afraid of what I might see.",
        "I can't wait for the Slowpoke Ball this year. It's going to be a magical night of dancing and enchantment.",
        'Do you know any good spells for making your homework write itself? Or an AI? I have way too many essays to finish.',
        'I just received a Howler from my parents for causing a ruckus in the Dorms. I hope they never find out about the incident in the potions lab.',
        "The giant squid in the Black Lake is massive! I wonder if it's friendly or if it ever comes up on land.",
        "I accidentally stepped on a Dreadthorne in Botania, and now I'm dealing with its disgusting stench. Ugh!",
        "I can't wait to learn about magical history and the great wizards and witches who shaped our world.",
        'I saw some upper-year students practicing the Cursed Glyph in the courtyard last night. It was a stunning display of powerful magic.',
        "I found a mysterious, ancient-looking book in the library. I'm trying to decipher the text, but it's written in a language I've never seen before.",
        "Do you think the rumors about the ghostly presence in the girl's bathroom are true? I heard Moaning Myrtle haunts it.",
        "The enchanted ceiling in the Great Hall is always fascinating to watch during meals. It's like having a real-time weather show.",
        "I'm excited for the Broom race this weekend. I hope Ignis Peak wins, but Aqua Haven has a strong team this year.",
        "I'm practicing the Engorgement Charm on my pet toad. Now it's three times its original size! I hope it goes back to normal...",
        'The enchanted suits of armor in the corridors give me the creeps, especially when they start moving on their own.',
        'Do you know about the cheating invocation some of the seniors got caught using last semester? I heard the incanation is Chaet Gjee Tee Pea',
        "I've been trying to brew the Flask of Crimson Shade, but it's a highly challenging potion. One mistake, and it could be disastrous!",
        'The magical plants in the greenhouse have a habit of misbehaving. One even tried to take a bite out of me during Botania class!',
        "I'm saving up my allowance to buy a new set of Wizarding Chess pieces. My current set has a mind of its own and keeps getting my disqualified!",
        "Do you think we'll ever get to meet the legendary beasts like the Hippogriff, Thunderbird, or the Nundu? That would be extraordinary!",
        "I heard that the Prefects' Bathroom is a hidden luxury with large, sparkling bathtubs. If only we could sneak in and use it just once!",
        'I wish I had the skill to become an Animagus like Professor Jake. Imagine being able to transform into an animal at will!',
        "I can't believe we have to take History of Magic. It's so boring, and Professor Binns is a ghost!",
        'I got detention for accidentally setting my cauldron on fire in the potions lab. Oops!',
        'Have you seen the enchanted ceiling in the Great Hall? It reflects the current weather outside!',
        "I hope we get to learn more about magical creatures like Hippogriffs and Nifflers in Beastmaster's class.",
        'Rumor has it that the Mirror of Erised shows you your deepest desires. I wonder what I would see.',
        'I wonder if the Room of Requirement could provide me with an endless supply of chocolate frogs.',
        'Glyphs are my favorite subject. Glyph of Launch is fun to cast, even though my feather flew all over the place.',
        "I'm still trying to master the Vanishing Spell. My toad keeps hopping away before I can make it disappear!",
        'I heard the Dinners are planning something big again. They always keep the place lively.',
        "I'm going to visit the greenhouse today. I hope I can find some rare magical herbs for my potion.",
        "Do you think the rumors about the haunted bathroom on the fifth floor are true? I don't want to find out!",
        "I'm determined to become an Animagus. It's challenging, but I can't resist the idea of transforming into an animal.",
        'Did you see the enchanted staircases moving around again? It took me ages to find my way to class!',
        "I've been practicing the Patronus charm, but all I can summon is a wisp of silver mist. It's frustrating.",
        "I wish I could attend Professor Aaronhowser1's EvilCraft class. It sounds fascinating, even if it's a bit messy.",
        'The Forbidden Forest is off-limits, but some students dare each other to venture in there at night.',
        "Careful with the Whomping Willow on the school grounds. It's got quite a temper!",
        'I heard the portraits in the castle come alive at night and have their own little parties.',
        "I can't wait for the Slowpoke Ball! It's going to be so much fun, especially with the enchanted decorations.",
        "I heard there's a hidden chamber somewhere in the castle, but no one seems to know how to find it.",
        "I'm excited for the magical dueling club. I want to practice some defensive spells.",
        'I wish Professor Slowpoke was still our Defense Against the Dark Arts teacher. He was the best!',
        "The enchanted ceiling in the Zephyr Heights Dorms shows the night sky. It's perfect for stargazing.",
        'Did you see the enchanted portraits in the Terra Crest Dorms? They love telling stories about the founders.',
        'Careful with Ghostipedia the Poltergeist; he loves playing pranks on unsuspecting students and teachers alike!',
    ],
    Yoshi: [
        'Yoshii~',
        'Yoshii~',
        'Yoshii~',
        'Yoshii~',
        'Yoshii~',
        'Yoshii~',
        "Actually my name is MiyoshiEira, but don't tell anyone",
    ],
    Toad: [
        'Welcome to the Mushroom Kingdom!',
        'Thank you! But our princess is in another castle!',
        'Oh no! The princess is in trouble!',
        'Hey, listen to me, Mario!',
        'Here, take this power-up to help you on your journey!... Ha! Fooled you!',
        'Watch out for those Zombies and Creepers!',
        'Good luck! You can do it!',
        'Princess Peach is counting on you!',
        'Jump on the flagpole at the end of the level to save your progress!',
        'Collect as many Gold as you can to earn extra lives!',
    ],
    'Prof. Jake': [
        "Welcome to the §6Beastmaster's class§r!\nI'm Professor Jake, and I'll be your teacher for this semester. Here you can get all the various Beasts and Animals you need for all the other Class",
    ],
    'Introduction Zora': [
        "Hello, I'm Zora, a Pixie of the Arcanum Institute. I'm here to help you get started on your magical journey. To get to the Dining Hall, you just follow the Path here.",
    ],
    'Luminizer Zora': [
        'To get to the Dining Hall, you can either take the §bLuminizer§r over there, or follow this scenic route!',
    ],
    'Dininghall Zora': [
        '\n§6All important dialogue is found in your Eccentric Tome!§r\nSome tasks do not have visible text until they are completed.\n§bOpen your Tome§r to the newly-completed task to read what the Teacher has to say!',
    ],
    'Dorm Zora': [
        'This is the Dorms area! Just go through any of these Portals to get to your Dorms!',
    ],
    'Goblin Zora': [
        'This is the Goblin Trader! You can buy all sorts of magical items here! Be sure to check out the Mob Gate Pearls and the raw Metal Blocks if you want to get started on your magical journey!',
    ],
    'Waypoint Zora': [
        'This Waypoint will show you the ways around the Arcanum Institute! There are plenty around. Some even have §bLuminizers§r to help you get around faster!',
    ],
}
